version: "3.7"

services:
  webserver:
    build: 
      context: ./bin/webserver
      args:
       USER: ${USER-newuser}
       TZ: ${USER-America/Santiago}
    container_name: 'webserver'
    tty: true
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - mysql
      - mssql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/etc/php/7.2/apache2/php.ini
      - ${APACHE_DIR_CONF-./config/apache/dir.conf}:/etc/apache2/mods-enabled/dir.conf
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${LETSENCRYPT_DIR-./config/letsencrypt}:/etc/letsencrypt
  mysql:
    build: ./bin/mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - ${MYSQL_PORT-3306}:3306
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE-newdb}
      MYSQL_USER: ${MYSQL_USER-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-secret}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${PMA_PORT-3306}
    ports:
      - ${PMA_WEB_PORT-8080}:80
    volumes: 
      - /sessions
  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - ${REDIS_PORT-6379}:6379
  dotnetcore:
    build:
      context: ./bin/dotnetcore
    container_name: 'dotnet'
    ports:
      - ${NETCORE_PORT-5000}:5000
    depends_on:
      - mssql
      - mysql
    volumes:
      - ${NETCORE_ROOT_DIR-./www/netcore}:/source
  mssql:
    image: "microsoft/mssql-server-linux"
    container_name: 'mssql'
    ports:
      - ${MSSQL_PORT-1433}:1433
    volumes: 
      - ${MSSQL_DATA_DIR-./data/mssql}:/var/opt/mssql
      - ${MSSQL_LOG_DIR-./logs/mssql}:/var/opt/mssql/log
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD-Yourpassword123}
      ACCEPT_EULA: "Y"
  openproject:
    image: "openproject/community:8"
    container_name: 'openproject'
    ports:
      - ${OP_PORT-4001}:80
    depends_on:
      - mysql
    volumes:
      - op_postgresql_data:/var/lib/postgresql/9.6/main
      - ./logs/openproject:/var/log/supervisor
    environment:
      EMAIL_DELIVERY_METHOD: ${EMAIL_DELIVERY_METHOD-Yourpassword123}
      SMTP_ADDRESS: ${SMTP_ADDRESS-smtp.example.net}
      SMTP_PORT: ${SMTP_PORT-587}
      SMTP_DOMAIN: ${SMTP_DOMAIN-example.net}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION-plain}
      SMTP_USER_NAME: ${SMTP_USER_NAME-user}
      SMTP_PASSWORD: ${SMTP_PASSWORD-password}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO-true}
volumes:
  op_postgresql_data: