version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
      args:
       USER: ${USER-newuser}
       TZ: ${USER-America/Santiago}
    container_name: 'webserver'
    tty: true
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/etc/php/7.2/apache2/php.ini
      - ${APACHE_DIR_CONF-./config/apache/dir.conf}:/etc/apache2/mods-enabled/dir.conf
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-available
      - ${APACHE_LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${LETSENCRYPT_DIR-./config/letsencrypt}:/etc/letsencrypt
  mysql:
    build: ./bin/mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - ${MYSQL_PORT-3306}:3306
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE-newdb}
      MYSQL_USER: ${MYSQL_USER-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-secret}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${PMA_PORT-3306}
    ports:
      - ${PMA_WEB_PORT-8080}:80
    volumes: 
      - /sessions
  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - ${REDIS_PORT-6379}:6379
  dotnetcore:
    build:
      context: ./bin/dotnetcore
    container_name: 'dotnet'
    ports:
      - ${NETCORE_PORT-5000}:5000
    depends_on:
      - mssql
    volumes:
      - ${NETCORE_ROOT_DIR-./www/netcore}:/source
  mssql:
    image: "microsoft/mssql-server-linux"
    container_name: 'mssql'
    ports:
      - ${MSSQL_PORT-1433}:1433
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD-Yourpassword123}
      ACCEPT_EULA: "Y"